export const POWER_WORDS: string[] = [
  "secret", "secrets", "revealed", "hidden", "untold",
  "insider", "exposed", "confidential", "classified",
  "amazing", "incredible", "unbelievable", "mind-blowing", "spectacular",
  "massive", "huge", "enormous", "ginormous", "colossal",
  "guaranteed", "proven", "scientific", "research", "study",
  "easy", "simple", "effortless", "painless", "quick",
  "ultimate", "complete", "definitive", "essential", "critical",
  "free", "bonus", "limited", "exclusive", "rare",
  "now", "today", "immediately", "instantly", "urgent",
  "worst", "terrible", "horrible", "disaster", "catastrophic",
  "revolutionary", "game-changing", "breakthrough",
  "dangerous", "risky", "scary", "terrifying", "deadly",
  "love", "hate", "fear", "greed", "lazy",
  "nobody", "everyone", "anyone", "someone", "everybody",
  "why", "how", "what", "when", "where",
  "stop", "start", "change", "transform", "convert",
  "never", "always", "forever", "ever", "every",
  "double", "triple", "quadruple", "multiply", "maximize",
  "destroy", "eliminate", "remove", "erase", "delete",
  "save", "protect", "preserve", "defend", "guard",
  "win", "beat", "dominate", "conquer", "crush",
  "discover", "unlock", "find", "reveal", "uncover",
  "boost", "skyrocket", "explode", "surge", "soar",
  "obsession", "addiction", "craze", "frenzy", "mania",
  "naked", "raw", "brutal", "honest", "unfiltered",
  "poverty", "wealth", "fortune", "riches", "millions",
  "shock", "stun", "astonish", "astound", "dumbfound",
  "genius", "brilliant", "master", "expert", "pro",
  "survive", "thrive", "flourish", "prosper", "bloom",
];
